import React from "react";
import ThemeProvider from "@/providers/ThemeProvider";
import PageLoader from "@/components/common/Loading/PageLoader";
import { IChildren } from "@/globalTypes";
import "./globals.css";

export const metadata = {
	title: "Next.js",
	description: "Generated by Next.js",
};

export default function RootLayout({ children }: IChildren) {
	return (
		<html lang="en">
			<body>
				<ThemeProvider>
					<PageLoader />
					{children}
				</ThemeProvider>
			</body>
		</html>
	);
}
